# XGBoost Model Configuration
model:
  _target_: xgboost.XGBRegressor
  
  # Core parameters
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 100
  
  # Regularization
  reg_lambda: 1.0
  reg_alpha: 0.0
  gamma: 0.0
  
  # Sampling
  subsample: 0.8
  colsample_bytree: 0.8
  
  # Other
  random_state: 42
  n_jobs: -1
  verbosity: 1

# Position-specific models
position_specific: true
positions:
  - GK
  - DEF  
  - MID
  - FWD
